# API Gateway - Cloud Build Pipeline
# Builds Docker image, pushes to Artifact Registry, deploys via Terraform

steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-image'
    secretEnv: ['NPM_TOKEN']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker build \
          --build-arg NPM_TOKEN="$$NPM_TOKEN" \
          -t ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO}/${_SERVICE_NAME}:${SHORT_SHA} \
          -t ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO}/${_SERVICE_NAME}:latest \
          .

  # Step 2: Push image (both tags)
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-image'
    args: ['push', '--all-tags', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO}/${_SERVICE_NAME}']

  # Step 3: Terraform init
  - name: 'hashicorp/terraform:1.9'
    id: 'tf-init'
    dir: 'deploy'
    args: ['init', '-input=false']

  # Step 4: Terraform plan
  - name: 'hashicorp/terraform:1.9'
    id: 'tf-plan'
    dir: 'deploy'
    args:
      - 'plan'
      - '-input=false'
      - '-var=container_image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO}/${_SERVICE_NAME}:${SHORT_SHA}'
      - '-out=tfplan'

  # Step 5: Terraform apply
  - name: 'hashicorp/terraform:1.9'
    id: 'tf-apply'
    dir: 'deploy'
    args: ['apply', '-input=false', 'tfplan']

substitutions:
  _REGION: 'europe-west1'
  _SERVICE_NAME: 'blich-api-gateway'
  _ARTIFACT_REPO: 'blich-studio'

availableSecrets:
  secretManager:
    - versionName: projects/${PROJECT_ID}/secrets/NPM_TOKEN_CLOUDBUILD/versions/latest
      env: 'NPM_TOKEN'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: 'CLOUD_LOGGING_ONLY'

timeout: '600s'
